'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class SchemaFiles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DBaddin.SchemaFiles", GetType(SchemaFiles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string from a DB addin central section (key/value pairs)
        '''</summary>
        Public Shared ReadOnly Property DBAddinCentral() As String
            Get
                Return ResourceManager.GetString("DBAddinCentral", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string from a DB addin user section (key/value pairs)
        '''</summary>
        Public Shared ReadOnly Property DBAddinUser() As String
            Get
                Return ResourceManager.GetString("DBAddinUser", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string from a DB Modifier definition conforming to the schema
        '''</summary>
        Public Shared ReadOnly Property DBModifDef() As String
            Get
                Return ResourceManager.GetString("DBModifDef", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string from a .net20 config setting
        '''</summary>
        Public Shared ReadOnly Property DotNetConfig20() As String
            Get
                Return ResourceManager.GetString("DotNetConfig20", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string for general settings
        '''</summary>
        Public Shared ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string for DBModif settings
        '''</summary>
        Public Shared ReadOnly Property SettingsDBModif() As String
            Get
                Return ResourceManager.GetString("SettingsDBModif", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
