'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class SchemaFiles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DBaddin.SchemaFiles", GetType(SchemaFiles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;xs:element name=&quot;appSettings&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element name=&quot;add&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:simpleContent&gt;
        '''              &lt;xs:extension base=&quot;xs:string&quot;&gt;
        '''                &lt;xs:attribute type=&quot;xs:string&quot; name=&quot;key&quot; use=&quot;required&quot;/&gt;
        '''                &lt;xs:attribute type=&quot;xs:string&quot; name=&quot;value&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property DBAddinCentral() As String
            Get
                Return ResourceManager.GetString("DBAddinCentral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;xs:element name=&quot;UserSettings&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element name=&quot;add&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
        '''          &lt;xs:complexType&gt;
        '''            &lt;xs:simpleContent&gt;
        '''              &lt;xs:extension base=&quot;xs:string&quot;&gt;
        '''                &lt;xs:attribute type=&quot;xs:string&quot; name=&quot;key&quot; use=&quot;required&quot;/&gt;
        '''                &lt;xs:attribute type=&quot;xs:string&quot; name=&quot;value [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property DBAddinUser() As String
            Get
                Return ResourceManager.GetString("DBAddinUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''	&lt;xs:element name=&quot;root&quot;&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:sequence&gt;
        '''				&lt;xs:choice maxOccurs=&quot;unbounded&quot; minOccurs=&quot;1&quot;&gt;
        '''					&lt;xs:element type=&quot;xs:string&quot; name=&quot;altDBImpl&quot; minOccurs=&quot;0&quot;/&gt;
        '''					&lt;xs:element name=&quot;DBAction&quot;&gt;
        '''						&lt;xs:complexType&gt;
        '''							&lt;xs:sequence&gt;
        '''								&lt;xs:choice maxOccurs=&quot;unbounded&quot; minOccurs=&quot;1&quot;&gt;
        '''									&lt;xs:element name=&quot;env&quot; minOccurs=&quot;0&quot;&gt;
        '''										&lt;xs:simpleType&gt;
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property DBModifDef() As String
            Get
                Return ResourceManager.GetString("DBModifDef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        '''&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:vs=&quot;http://schemas.microsoft.com/Visual-Studio-Intellisense&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; vs:helpNamespace=&quot;http://schemas.microsoft.com/.NetConfiguration/v2.0&quot;&gt;
        '''    &lt;xs:element name=&quot;configuration&quot;&gt;
        '''        &lt;xs:complexType&gt;
        '''            &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''                &lt;xs:any namespace=&quot;##any&quot; processContents=&quot;lax&quot; /&gt;
        '''            &lt;/ [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property DotNetConfig20() As String
            Get
                Return ResourceManager.GetString("DotNetConfig20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdHocSQLTransferType
        '''AdHocSQLcmdDB + AdHocSQLStringsIndex
        '''AdHocSQLcmdEnv + AdHocSQLStringsIndex
        '''AltConnString + env
        '''AvoidUpdateLinks_Refresh
        '''AvoidUpdateListObjects_Refresh
        '''AvoidUpdatePivotTables_Refresh
        '''AvoidUpdateQueryTables_Refresh
        '''CmdTimeout
        '''CnnTimeout
        '''ConfigName + env
        '''ConfigSelect
        '''ConfigSelect + ConfigSelectPreference
        '''ConfigSelectPreference
        '''ConfigStoreFolder + env
        '''ConnStringReplace + env
        '''ConnStringSearch + env
        '''ConstConnString + env
        '''DBMapperCUDFlagStyle
        '''DBMapperStandardStyle
        '''DBSheetCo [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
